GPU available: True, used: True
TPU available: None, using: 0 TPU cores
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
Using native 16bit precision.

  | Name      | Type             | Params
-----------------------------------------------
0 | criterion | CrossEntropyLoss | 0     
1 | block1    | Sequential       | 304   
2 | block2    | Sequential       | 4.1 K 
3 | block3    | Sequential       | 8.3 K 
4 | block4    | Sequential       | 33.0 K
5 | dense1    | Linear           | 164 K 
6 | dense2    | Linear           | 1.0 K 
-----------------------------------------------
210 K     Trainable params
0         Non-trainable params
210 K     Total params
Validation sanity check: 0it [00:00, ?it/s]Traceback (most recent call last):
  File ".\src\models\CNN.py", line 81, in <module>
    train()
  File ".\src\models\CNN.py", line 72, in train
    trainer.fit(model, train_dataloader, validation_dataloader)
  File "C:\ProgramData\Miniconda3\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 473, in fit
    results = self.accelerator_backend.train()
  File "C:\ProgramData\Miniconda3\lib\site-packages\pytorch_lightning\accelerators\gpu_accelerator.py", line 66, in train
    results = self.train_or_test()
  File "C:\ProgramData\Miniconda3\lib\site-packages\pytorch_lightning\accelerators\accelerator.py", line 69, in train_or_test
    results = self.trainer.train()
  File "C:\ProgramData\Miniconda3\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 495, in train
    self.run_sanity_check(self.get_model())
  File "C:\ProgramData\Miniconda3\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 693, in run_sanity_check
    _, eval_results = self.run_evaluation(test_mode=False, max_batches=self.num_sanity_val_batches)
  File "C:\ProgramData\Miniconda3\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 609, in run_evaluation
    output = self.evaluation_loop.evaluation_step(test_mode, batch, batch_idx, dataloader_idx)
  File "C:\ProgramData\Miniconda3\lib\site-packages\pytorch_lightning\trainer\evaluation_loop.py", line 178, in evaluation_step
    output = self.trainer.accelerator_backend.validation_step(args)
  File "C:\ProgramData\Miniconda3\lib\site-packages\pytorch_lightning\accelerators\gpu_accelerator.py", line 84, in validation_step
    return self._step(self.trainer.model.validation_step, args)
  File "C:\ProgramData\Miniconda3\lib\site-packages\pytorch_lightning\accelerators\gpu_accelerator.py", line 74, in _step
    output = model_step(*args)
  File "K:\OneDrive - Cumberland Valley School District\Education\Activates\Science Fair\PCG-Science-Fair\PCG-arrhythmia-detection\src\models\pblm.py", line 64, in validation_step
    metrics = self.metrics_step(outputs, targets, prefix="validation-")
  File "K:\OneDrive - Cumberland Valley School District\Education\Activates\Science Fair\PCG-Science-Fair\PCG-arrhythmia-detection\src\models\pblm.py", line 100, in metrics_step
    accuracy_score = accuracy(pred, targets)
  File "C:\ProgramData\Miniconda3\lib\site-packages\pytorch_lightning\metrics\functional\classification.py", line 264, in accuracy
    tps, fps, tns, fns, sups = stat_scores_multiple_classes(
  File "C:\ProgramData\Miniconda3\lib\site-packages\pytorch_lightning\metrics\functional\classification.py", line 174, in stat_scores_multiple_classes
    num_classes = get_num_classes(pred=pred, target=target, num_classes=num_classes)
  File "C:\ProgramData\Miniconda3\lib\site-packages\pytorch_lightning\metrics\functional\classification.py", line 84, in get_num_classes
    return __gnc(pred,target, num_classes)
  File "C:\ProgramData\Miniconda3\lib\site-packages\pytorch_lightning\metrics\utils.py", line 214, in get_num_classes
    num_target_classes = int(target.max().detach().item() + 1)
RuntimeError: CUDA error: device-side assert triggered
